### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by akashk92** [osama-raddad/FireCrasher#2]
I am raising NPE in launcher activity but my app still crashes..

**Comment by osama-raddad** [comment]
you need to add the library integration in the Application class and only in the  Application class and before the `super.onCreate()`

**Comment by akashk92** [comment]
yes I am doing FireCrasher.install(this); in Application Class
and raising NPE in launcher activity

**Comment by osama-raddad** [comment]
is it specific exception  that crashes the app or the app crashes on every exception , and check please if 
you are resetting the default uncaught exception handler , and please send me the the exception row

**Comment by akashk92** [comment]
I get Null Pointer Exception (Intentionally throwing...) to see the the library working and
what do you mean by "resetting the default uncaught exception handler"?

**Comment by osama-raddad** [comment]
You might be using a library that change the uncaught exception handler that i use

**Comment by mradzinski** [comment]
Having exactly the same issue: app crashes, the only difference is that I don't get a message, it just closes and displays the toast I set. The only library I'm using aside of yours is Crashlytics, so there's nothing changing your uncaught exception.

Here's my listener code, I'm "installing" FireCrasher on my App class before super.onCreate:

```
            override fun onCrash(throwable: Throwable, activity: Activity) {
                Toast.makeText(activity, "Ups! something went wrong", Toast.LENGTH_LONG).show()
                recover(activity)
                Crashlytics.logException(throwable)
            }
```

I guess the issue is due to the fact that **recover()** method variable **ActivityInfo[] list** will always have more than one element length-wise and you are always evaluating "if only has 1 and the position 0 of that array name equals to the name of the activity who threw the exception" and that's most of the time always false (App's have more than one activity).

Here's where I think the issue is: https://github.com/osama-raddad/FireCrasher/blob/master/firecrasher/src/main/java/com/osama/firecrasher/FireCrasher.java#L37-L42

**Comment by osama-raddad** [comment]
thanks man for the kind words , i use in the library a recovering logic that checks for the activity that happened in it the crash if it is the only activity that is started or if there is a activities in the back stack 
`if (list.length == 1 && list[0].name.equals(activity.getClass().getName()))`  
that is the job of this if statement and i test it and it is working perfectly
if my uncaught exception is working and the recover method is not working your app will freeze
please send me the brand and the model of your testing device and  do you see a message like this  
[http://d38v16rqg5mb6e.cloudfront.net/wp-content/uploads/2015/06/Galaxy-S5-Contact-Has-Stopped.jpg](url)

**Comment by akashk92** [comment]
motorola (verizon) DROID RAZR M this is my testing device

and your above url is not working
